<?php

return [
	'BOOK_ALREADY_LOANED' => 1,
	'USER_FINE_PENDING' => 2,
	'USER_QUOTA_FULL' => 3,
	'BOOK_NOT_FOUND' => 101,
	'USER_NOT_FOUND' => 102,
    'HTTP_BAD_REQUEST_STATUS_CODE' => 400,
	'HTTP_AUTHENTICATION_FAILED_STATUS_CODE' => 401,
	'HTTP_NOT_FOUND_STATUS_CODE' => 404,
	'HTTP_INTERNAL_SERVER_ERROR' => 500,
];