<?php

return [
	'INVALID_OPERATION' => 0,
	'BOOK_ALREADY_LOANED' => 1,
	'BOOK_ALREADY_RETURNED' => 2,
	'USER_FINE_PENDING' => 3,
	'USER_QUOTA_FULL' => 4,
	'BOOK_NOT_FOUND' => 101,
	'USER_NOT_FOUND' => 102,
	'BOOK_ALREADY_EXISTS' => 151,
	'USER_ALREADY_EXISTS' => 152,
    'HTTP_BAD_REQUEST_STATUS_CODE' => 400,
	'HTTP_AUTHENTICATION_FAILED_STATUS_CODE' => 401,
	'HTTP_NOT_FOUND_STATUS_CODE' => 404,
	'HTTP_INTERNAL_SERVER_ERROR' => 500,
];